### PR TITLE
Replace "state" with "place"

### LINKED ISSUE #8: Change "state" variables etc. to something abstracted
Not "place," because a census might of various agencies in a given city (for instance). Come up with a generic term to describe the entity being surveyed.

### PR DESCRIPTION
**Pull request by ondrae**
This PR changes "state" with "place" in all of the code, yet leaves the copy alone.

The one trick is you must change the name of the State column to Place on [your spreadsheet](https://docs.google.com/spreadsheets/d/1OhVbryeHBsPjJ3TjjVFlfM552pDKRjiUpTAXQJe9miA/edit#gid=1723589224).

Closes #8

### CODE REVIEW

**Comment by ondrae** [comment]
Now that I read #8 I see you already thought through this and recommended against place. Whoops.

I'll make the switch to use `entity` instead, probably tomorrow.

**Comment by waldoj** [comment]
Well, only if you agree. :) If you think `place` is better, I'm open to that!

**Comment by ondrae** [comment]
I think I like "place".

Looking at the five existing censuses, they are all talking about places. Your idea of doing city departments within a place makes sense, yet hasn't really happened that we've seen. "place" is a little less confusing than "entity". Cool?

**Comment by waldoj** [comment]
Great idea, looking at existing censuses. "Place" it is!

**Pull request merged**
